// N1 Quiz bank
export const n1Quiz = [
  { id: 'n1q01', level: 'N1', skill: 'vocab', question: '「慨念」の読み方は？', options: ['がいねん', 'そくばく', 'かいほう', 'だんあつ'], correctIndex: 0, explanation: '慨念（がいねん）= အယူအဆ' },
  { id: 'n1q02', level: 'N1', skill: 'vocab', question: '「捏造」の意味は？', options: ['လုပ်ကြံဖန်တီးမှု', 'တန်ဖိုးဖြတ်မှု', 'စစ်ဆေးမှု', 'ခန့်မှန်းချက်'], correctIndex: 0, explanation: '捏造（ねつぞう）= လုပ်ကြံဖန်တီးမှု' },
  { id: 'n1q03', level: 'N1', skill: 'vocab', question: '「朴訥」の読み方は？', options: ['ぼくとつ', 'そぼく', 'しっそ', 'かんそ'], correctIndex: 0, explanation: '朴訥（ぼくとつ）= ရိုးအေးသော' },
  { id: 'n1q04', level: 'N1', skill: 'grammar', question: '彼 ___ できる芸当ではない。', options: ['にして', 'なくして', 'にあって', 'をもって'], correctIndex: 1, explanation: '〜なくしては = without (သူ မပါဘဲ မဖြစ်နိုင်တဲ့ စွမ်းဆောင်မှု)' },
  { id: 'n1q05', level: 'N1', skill: 'grammar', question: '努力 ___ 成功はない。', options: ['なくして', 'なしに', 'ぬきに', 'をとわず'], correctIndex: 0, explanation: '〜なくして（は）〜ない = without…no (ကြိုးစားမှုမရှိဘဲ အောင်မြင်မှုမရှိ)' },
  { id: 'n1q06', level: 'N1', skill: 'reading', question: '筆者が批判しているのは何か。', passage: '情報を鵜呑みにする風潮が広がっている。吟味せずに拡散する行為こそが、誤解を生む最大の原因だと筆者は考える。', options: ['情報が少ないこと', '吟味せず拡散する行為', '筆者の考え', '誤解が解けること'], correctIndex: 1, explanation: '吟味せずに拡散する行為こそが…原因' },
  { id: 'n1q07', level: 'N1', skill: 'listening', question: '聞こえた内容は？', speakText: 'しめきりはらいしゅうの金曜日です', options: ['今週の金曜日', '来週の金曜日', '来週の月曜日', '期限なし'], correctIndex: 1, explanation: '締め切りは来週の金曜日 = နောက်အပတ် သောကြာ' },
  { id: 'n1q08', level: 'N1', skill: 'vocab', question: '「横領」の意味は？', options: ['အလွဲသုံးစားမှု', 'လာဘ်ထိုးမှု', 'အတုလုပ်မှု', 'ခြိမ်းခြောက်မှု'], correctIndex: 0, explanation: '横領（おうりょう）= အလွဲသုံးစားမှု' },
  { id: 'n1q09', level: 'N1', skill: 'vocab', question: '「錆」の読み方は？', options: ['さび', 'あか', 'すす', 'ほこり'], correctIndex: 0, explanation: '錆（さび）= သံချေး' },
  { id: 'n1q10', level: 'N1', skill: 'vocab', question: '「枯渇」の意味は？', options: ['ခန်းခြောက်မှု', 'တီထွင်မှု', 'ရှာဖွေတွေ့ရှိမှု', 'ဖွံ့ဖြိုးမှု'], correctIndex: 0, explanation: '枯渇（こかつ）= ခန်းခြောက်မှု' },
  { id: 'n1q11', level: 'N1', skill: 'grammar', question: '親の反対 ___ 結婚した。', options: ['を押し切って', 'をもとに', 'をかねて', 'を限りに'], correctIndex: 0, explanation: '〜を押し切って = pushing aside opposition (ဆန့်ကျင်မှုကို တွန်းလှန်ပြီး)' },
  { id: 'n1q12', level: 'N1', skill: 'grammar', question: '彼は来ない ___ 連絡もない。', options: ['うえに', 'ばかりか', 'どころか', 'かたわら'], correctIndex: 0, explanation: '〜うえに = besides/in addition (မလာတဲ့အပြင် အကြောင်းလည်းမကြား)' },
  { id: 'n1q13', level: 'N1', skill: 'reading', question: '筆者はAIについてどう考えているか。', passage: 'AIは便利だが、使い方を誤ると危険だ。だからこそ、人間の判断がますます重要になると筆者は述べている。', options: ['AIは不要だ', '使い方次第で人間の判断が重要', 'AIに任せればいい', '危険なので禁止すべき'], correctIndex: 1, explanation: '人間の判断がますます重要' },
  { id: 'n1q14', level: 'N1', skill: 'listening', question: '聞こえた内容は？', speakText: 'かいぎしつは三階の奥です', options: ['一階', '二階', '三階の奥', '外'], correctIndex: 2, explanation: '三階の奥 = ၃ လွှာ အတွင်းဘက်' },
  { id: 'n1q15', level: 'N1', skill: 'vocab', question: '「埃」の読み方は？', options: ['ほこり', 'あか', 'すす', 'かび'], correctIndex: 0, explanation: '埃（ほこり）= ဖုန်မှုန့်' },
  { id: 'n1q16', level: 'N1', skill: 'vocab', question: '「研ぐ」の意味は？', options: ['သွေးသည် (ဓား)', 'ပွတ်တိုက်သည်', 'နှိပ်နယ်သည်', 'လိမ်သည်'], correctIndex: 0, explanation: '研ぐ（とぐ）= သွေးသည်' },
  { id: 'n1q17', level: 'N1', skill: 'grammar', question: '努力した ___ 合格できた。', options: ['甲斐あって', '甲斐なく', '末に', '次第で'], correctIndex: 0, explanation: '〜甲斐あって = efforts paid off' },
  { id: 'n1q18', level: 'N1', skill: 'grammar', question: '感動して泣き出さん ___ にした。', options: ['ばかり', 'ばかりか', 'ばかりで', 'ばかりの'], correctIndex: 0, explanation: '〜んばかりに = as if about to (泣き出さんばかり)' },
  { id: 'n1q19', level: 'N1', skill: 'reading', question: '筆者が最も言いたいことは？', passage: '便利さばかり追うと、大切なものを失う。少し不便でも、手をかける暮らしにこそ豊かさがあると筆者は説く。', options: ['便利が一番だ', '手をかける暮らしに豊かさがある', '不便は悪いことだ', '豊かさは要らない'], correctIndex: 1, explanation: '手をかける暮らしにこそ豊かさがある' },
  { id: 'n1q20', level: 'N1', skill: 'listening', question: '聞こえた内容は？', speakText: 'でんしゃが十分おくれています', options: ['定刻通り', '十分遅れ', '運休', '満員'], correctIndex: 1, explanation: '十分（じゅうぶん）遅れています' },
  { id: 'n1q21', level: 'N1', skill: 'vocab', question: '「邂逅」の読み方は？', options: ['かいこう', 'かいごう', 'こうかい', 'きかい'], correctIndex: 0, explanation: '邂逅（かいこう）= မမျှော်လင့်ဘဲတွေ့ဆုံမှု' },
  { id: 'n1q22', level: 'N1', skill: 'grammar', question: '混沌 ___ した時代に、新しい思想が生まれた。', options: ['ときわ', 'と化', 'と化した', 'とする'], correctIndex: 2, explanation: '〜と化した = …အဖြစ်သို့ပြောင်းသွားသော (混沌と化した時代)' },
  { id: 'n1q23', level: 'N1', skill: 'reading', question: '筆者の主張は？', passage: '刹那的な快楽を追う生き方は、結局虚無しか残さない。永劫に残る価値を求めるなら、日々の小さな積み重ねこそが、混沌とした時代を生き抜く力になると筆者は論じる。', options: ['快楽だけ追え', '日々の積み重ねが力になる', '価値は求めるな', '時代は変えられない'], correctIndex: 1, explanation: '日々の小さな積み重ねこそが力になる' },
  { id: 'n1q24', level: 'N1', skill: 'vocab', question: '「黄昏」の読み方は？', options: ['たそがれ', 'れいめい', 'せつな', 'こんとん'], correctIndex: 0, explanation: '黄昏（たそがれ）= ဆည်းဆာချိန်' },
  { id: 'n1q25', level: 'N1', skill: 'grammar', question: '永劫に残る価値を ___、日々努力する。', options: ['求め', '求めて', '求めつつ', '求めたら'], correctIndex: 1, explanation: '求めて (te-form + 日々努力する)' },
  { id: 'n1q26', level: 'N1', skill: 'listening', question: '聞こえた言葉は？', speakText: 'かいこうをたのしみにしています', options: ['邂逅を楽しみにしている', '改革を楽しみにしている', '開港を楽しみにしている', '快復を楽しみにしている'], correctIndex: 0, explanation: '邂逅（かいこう）= တွေ့ဆုံမှု' },
];
