// N2 Quiz bank
export const n2Quiz = [
  { id: 'n2q01', level: 'N2', skill: 'vocab', question: '「躊躇」の読み方は？', options: ['ちゅうちょ', 'けつだん', 'かくご', 'はんせい'], correctIndex: 0, explanation: '躊躇（ちゅうちょ）= တွေဝေမှု' },
  { id: 'n2q02', level: 'N2', skill: 'vocab', question: '「平等」の意味は？', options: ['မျှတမှု', 'တန်းတူညီမျှမှု', 'တရားမျှတမှု', 'အမှန်တရား'], correctIndex: 1, explanation: '平等（びょうどう）= တန်းတူညီမျှမှု' },
  { id: 'n2q03', level: 'N2', skill: 'vocab', question: '「乏しい」の意味は？', options: ['ပေါများသော', 'ချို့တဲ့သော', 'တိကျသော', 'ရိုးရှင်းသော'], correctIndex: 1, explanation: '乏しい（とぼしい）= ချို့တဲ့သော' },
  { id: 'n2q04', level: 'N2', skill: 'grammar', question: '雨が降る ___ 、試合は中止だ。', options: ['につき', 'かぎり', '以上', '次第'], correctIndex: 2, explanation: '〜以上 = since (မိုးရွာနေတာကြောင့် ပွဲဖျက်တယ်)' },
  { id: 'n2q05', level: 'N2', skill: 'grammar', question: '彼は来る ___ 来ない ___ はっきりしない。', options: ['か / か', 'と / と', 'や / や', 'の / の'], correctIndex: 0, explanation: '〜か〜か = whether or not (လာမလား မလာဘူးလား မသေချာဘူး)' },
  { id: 'n2q06', level: 'N2', skill: 'grammar', question: 'この仕事は私 ___ できる。', options: ['にしては', 'にとっては', 'としては', 'からしては'], correctIndex: 1, explanation: '〜にとっては = for (ငါ့အတွက်တော့ လုပ်နိုင်တယ်)' },
  { id: 'n2q07', level: 'N2', skill: 'reading', question: '筆者の主張はどれですか。', passage: '技術が進んでも、人の心を理解することは機械にはできない。だからこそ、コミュニケーションの力を育てる教育が大切だ。', options: ['技術だけ学べばいい', '機械に任せればいい', 'コミュニケーション教育が大切だ', '心は理解できる'], correctIndex: 2, explanation: 'コミュニケーションの力を育てる教育が大切だ' },
  { id: 'n2q08', level: 'N2', skill: 'reading', question: '機械にできないことは何ですか。', passage: '技術が進んでも、人の心を理解することは機械にはできない。だからこそ、コミュニケーションの力を育てる教育が大切だ。', options: ['計算すること', '人の心を理解すること', '教育すること', '進むこと'], correctIndex: 1, explanation: '人の心を理解することは機械にはできない' },
  { id: 'n2q09', level: 'N2', skill: 'listening', question: '聞こえた内容は？', speakText: 'かいぎは三時から四時までです', options: ['2時から3時まで', '三時から四時まで', '4時から5時まで', '時間は未定'], correctIndex: 1, explanation: '三時から四時まで = ၃ နာရီကနေ ၄ နာရီအထိ' },
  { id: 'n2q10', level: 'N2', skill: 'vocab', question: '「妥協」の意味は？', options: ['အလျှော့ပေးမှု', 'သဘောတူမှု', 'ငြင်းပယ်မှု', 'အတည်ပြုမှု'], correctIndex: 0, explanation: '妥協（だきょう）= အလျှော့ပေးမှု' },
  { id: 'n2q11', level: 'N2', skill: 'vocab', question: '「猶予」の読み方は？', options: ['ゆうよ', 'よゆう', 'きゅうよ', 'きゅうか'], correctIndex: 0, explanation: '猶予（ゆうよ）= ဆိုင်းငံ့ခွင့်' },
  { id: 'n2q12', level: 'N2', skill: 'vocab', question: '「好転」の意味は？', options: ['တိုးတက်ကောင်းမွန်လာမှု', 'ဆိုးဝါးလာမှု', 'လျော့ပါးမှု', 'အကျပ်ဖြေရှင်းမှု'], correctIndex: 0, explanation: '好転（こうてん）= တိုးတက်ကောင်းမွန်လာမှု' },
  { id: 'n2q13', level: 'N2', skill: 'grammar', question: '努力 ___ 成功した。', options: ['の末に', 'の際に', 'のたびに', 'のかわりに'], correctIndex: 0, explanation: '努力の末に = ကြိုးစားမှုရဲ့ အဆုံးမှာ (finally)' },
  { id: 'n2q14', level: 'N2', skill: 'grammar', question: '雨が降ろう ___ 試合をする。', options: ['が', 'と', 'や', 'のを'], correctIndex: 0, explanation: '〜ろうが〜まいが = whether or not (ရွာသည်ဖြစ်စေ...)' },
  { id: 'n2q15', level: 'N2', skill: 'reading', question: '男の人はなぜ残業しましたか。', passage: '締め切りが明日なので、男の人は今日残業して資料を作りました。', options: ['締め切りが明日だから', '暇だから', '会議があるから', '給料のため'], correctIndex: 0, explanation: '締め切りが明日なので' },
  { id: 'n2q16', level: 'N2', skill: 'listening', question: '聞こえた内容は？', speakText: 'しんごうがあおになったらわたってください', options: ['赤で渡る', '青で渡る', '黄色で渡る', '渡らない'], correctIndex: 1, explanation: '青になったら = မီးစိမ်းရင်' },
  { id: 'n2q17', level: 'N2', skill: 'vocab', question: '「門出」の読み方は？', options: ['かどで', 'ふなで', 'たびだち', 'さいき'], correctIndex: 0, explanation: '門出（かどで）= အစပြုခြင်း' },
  { id: 'n2q18', level: 'N2', skill: 'vocab', question: '「緩和」の意味は？', options: ['လျော့ပါးစေမှု', 'ပြင်းထန်လာမှု', 'တိုးတက်မှု', 'ဆိုးဝါးလာမှု'], correctIndex: 0, explanation: '緩和（かんわ）= လျော့ပါးစေမှု' },
  { id: 'n2q19', level: 'N2', skill: 'grammar', question: '彼の成功は努力の ___ だ。', options: ['たまもの', 'すえ', 'かぎり', 'きわみ'], correctIndex: 0, explanation: '〜のたまものだ = thanks to (effort のおかげ)' },
  { id: 'n2q20', level: 'N2', skill: 'grammar', question: '知らない人に話しかけられて、 ___ した。', options: ['どぎまぎ', 'はらはら', 'そわそわ', 'うろうろ'], correctIndex: 0, explanation: 'どぎまぎする = ရင်ခုန်စိုးရိမ်သည်' },
  { id: 'n2q21', level: 'N2', skill: 'reading', question: '店が閉まった理由は？', passage: '人手不足のため、店は来月閉まることになりました。常連客は残念がっています。', options: ['人手不足のため', '売上が悪いため', '移転のため', '改装のため'], correctIndex: 0, explanation: '人手不足のため' },
  { id: 'n2q22', level: 'N2', skill: 'listening', question: '聞こえた金額は？', speakText: 'ぜんぶで千五百円です', options: ['五百円', '千円', '千五百円', '二千円'], correctIndex: 2, explanation: '千五百円（せんごひゃくえん）' },
];
