// N3 Quiz bank
export const n3Quiz = [
  { id: 'n3q01', level: 'N3', skill: 'vocab', question: '「景色」の読み方は？', options: ['けしき', 'しぜん', 'うちゅう', 'ちきゅう'], correctIndex: 0, explanation: '景色（けしき）= ရှုခင်း' },
  { id: 'n3q02', level: 'N3', skill: 'vocab', question: '「期限」の意味は？', options: ['ကာလ', 'သတ်မှတ်ရက်', 'အစီအစဉ်', 'ရလဒ်'], correctIndex: 1, explanation: '期限（きげん）= သတ်မှတ်ရက် (deadline)' },
  { id: 'n3q03', level: 'N3', skill: 'vocab', question: '「挨拶」の読み方は？', options: ['あいさつ', 'かんしゃ', 'きぼう', 'よてい'], correctIndex: 0, explanation: '挨拶（あいさつ）= နှုတ်ဆက်စကား' },
  { id: 'n3q04', level: 'N3', skill: 'vocab', question: '「曖昧」の意味は？', options: ['ထင်ရှားသော', 'မရေမရာသော', 'မှန်ကန်သော', 'တင်းကျပ်သော'], correctIndex: 1, explanation: '曖昧（あいまい）= မရေမရာသော' },
  { id: 'n3q05', level: 'N3', skill: 'grammar', question: '雨 ___ 降り出した。', options: ['が', 'を', 'に', 'へ'], correctIndex: 0, explanation: '自然現象 + が (雨が降り出した)' },
  { id: 'n3q06', level: 'N3', skill: 'grammar', question: '彼は来ない ___ 思う。', options: ['と', 'に', 'を', 'が'], correctIndex: 0, explanation: '引用 + と思う (〜と思う)' },
  { id: 'n3q07', level: 'N3', skill: 'grammar', question: 'この問題は難し ___ 、できません。', options: ['すぎて', 'すぎる', 'すぎ', 'すぎた'], correctIndex: 0, explanation: '〜すぎて〜できない = too…to (ခက်လွန်းလို့ မလုပ်နိုင်ဘူး)' },
  { id: 'n3q08', level: 'N3', skill: 'grammar', question: '薬を飲んだ ___ 、熱が下がった。', options: ['おかげで', 'せいで', 'ために', 'ように'], correctIndex: 0, explanation: 'おかげで = thanks to (ကောင်းသောရလဒ်); せいで = unfortunately because' },
  { id: 'n3q09', level: 'N3', skill: 'reading', question: '筆者は何を一番伝えたいですか。', passage: '日本語の勉強で一番大切なのは、毎日少しずつ続けることです。一日に10分でもいいから、休まないでください。', options: ['長い時間勉強すること', '毎日続けること', '文法だけ覚えること', '休むこと'], correctIndex: 1, explanation: '毎日少しずつ続けること = နေ့တိုင်းနည်းနည်းဆက်လုပ်ဖို့' },
  { id: 'n3q10', level: 'N3', skill: 'reading', question: '一日に何分でもいいと言っていますか。', passage: '日本語の勉強で一番大切なのは、毎日少しずつ続けることです。一日に10分でもいいから、休まないでください。', options: ['5分', '10分', '30分', '1時間'], correctIndex: 1, explanation: '一日に10分でもいい' },
  { id: 'n3q11', level: 'N3', skill: 'listening', question: '男の人は明日何をしますか。', speakText: 'あしたは会議がありますから、はやく来てください', options: ['会議があります', '休みます', '出張します', '何もしません'], correctIndex: 0, explanation: 'あしたは会議があります' },
  { id: 'n3q12', level: 'N3', skill: 'vocab', question: '「努力」の読み方は？', options: ['どりょく', 'がまん', 'きぼう', 'けいかく'], correctIndex: 0, explanation: '努力（どりょく）= ကြိုးစားအားထုတ်မှု' },
  { id: 'n3q13', level: 'N3', skill: 'vocab', question: '「余裕」の読み方は？', options: ['よゆう', 'よち', 'よぶん', 'よけい'], correctIndex: 0, explanation: '余裕（よゆう）= အပိုအလျှံ / စိတ်အေးမှု' },
  { id: 'n3q14', level: 'N3', skill: 'vocab', question: '「建前」の意味は？', options: ['အများရှေ့ဟန်ဆောင်', 'အမှန်တရား', 'ဂုဏ်', 'အလှ'], correctIndex: 0, explanation: '建前（たてまえ）= အများရှေ့ဟန်ဆောင် ⇔ 本音' },
  { id: 'n3q15', level: 'N3', skill: 'grammar', question: 'この仕事は一人では多すぎて、一日では終わり ___ ない。', options: ['きら', 'きれ', 'きり', 'きろ'], correctIndex: 0, explanation: '〜きらない = endless (終わりきらない = ပြီးနိုင်မှာမဟုတ်ဘူး)' },
  { id: 'n3q16', level: 'N3', skill: 'grammar', question: '日本語が上手 ___ なりたい。', options: ['に', 'へ', 'を', 'が'], correctIndex: 0, explanation: '変化 + に (上手になる = တော်လာတယ်)' },
  { id: 'n3q17', level: 'N3', skill: 'reading', question: '地震のとき、まず何をしますか。', passage: '地震のときは、まず机の下に入ります。火を消して、ドアを開けます。', options: ['机の下に入る', '外に走る', '電話する', '寝る'], correctIndex: 0, explanation: 'まず机の下に入ります' },
  { id: 'n3q18', level: 'N3', skill: 'listening', question: '聞こえた期限は？', speakText: 'しゅくだいはあしたまでです', options: ['今日まで', 'あしたまで', 'あさってまで', '毎日'], correctIndex: 1, explanation: 'あしたまで = မနက်ဖြန်အထိ' },
  { id: 'n3q19', level: 'N3', skill: 'vocab', question: '「照れる」の意味は？', options: ['ရှက်သည်', 'စိတ်ဆိုးသည်', 'ရယ်သည်', 'ငိုသည်'], correctIndex: 0, explanation: '照れる（てれる）= ရှက်သည်' },
  { id: 'n3q20', level: 'N3', skill: 'grammar', question: '子供のころ、よく川 ___ 泳いだ。', options: ['で', 'に', 'へ', 'を'], correctIndex: 0, explanation: '動作の場所 + で (川で泳いだ)' },
  { id: 'n3q21', level: 'N3', skill: 'vocab', question: '「本音」の読み方は？', options: ['ほんね', 'たてまえ', 'ていさい', 'みえ'], correctIndex: 0, explanation: '本音（ほんね）= ရင်ထဲကအမှန် ⇔ 建前' },
  { id: 'n3q22', level: 'N3', skill: 'vocab', question: '「余裕」の意味は？', options: ['အပိုအလျှံ', 'အပို', 'ပိုနေသော', 'နေရာလွတ်'], correctIndex: 0, explanation: '余裕（よゆう）= အပိုအလျှံ / စိတ်အေးမှု' },
  { id: 'n3q23', level: 'N3', skill: 'grammar', question: 'この店はいつも込んでいて、座る ___ がない。', options: ['席', '余裕', '余白', '余地'], correctIndex: 0, explanation: '座る席がない = ထိုင်စရာနေရာမရှိ' },
  { id: 'n3q24', level: 'N3', skill: 'grammar', question: '試験が終わって、 ___ した。', options: ['ほっと', 'どきどき', 'わくわく', 'いらいら'], correctIndex: 0, explanation: 'ほっとする = စိတ်အေးရသည်' },
  { id: 'n3q25', level: 'N3', skill: 'reading', question: '女の人はなぜ泣きましたか。', passage: '映画がとても感動的で、女の人は泣きました。隣の男の人は笑っていました。', options: ['感動したから', '悲しかったから', '笑ったから', '怒ったから'], correctIndex: 0, explanation: '感動的で…泣きました' },
  { id: 'n3q26', level: 'N3', skill: 'reading', question: '男の人はどうしましたか。', passage: '映画がとても感動的で、女の人は泣きました。隣の男の人は笑っていました。', options: ['泣いた', '笑っていた', '寝ていた', '帰った'], correctIndex: 1, explanation: '隣の男の人は笑っていました' },
  { id: 'n3q27', level: 'N3', skill: 'listening', question: '聞こえた曜日は？', speakText: 'かいぎは水曜日です', options: ['火曜日', '水曜日', '木曜日', '金曜日'], correctIndex: 1, explanation: '水曜日（すいようび）' },
  { id: 'n3q28', level: 'N3', skill: 'vocab', question: '「慌てる」の意味は？', options: ['အလန့်တကြားဖြစ်သည်', 'အလျင်လိုသည်', 'စိတ်ငြိမ်သည်', 'ပျင်းရိသည်'], correctIndex: 0, explanation: '慌てる（あわてる）= အလန့်တကြားဖြစ်သည်' },
  { id: 'n3q29', level: 'N3', skill: 'vocab', question: '「曖昧」の読み方は？', options: ['あいまい', 'あまい', 'まいあい', 'あいみ'], correctIndex: 0, explanation: '曖昧（あいまい）= မရေရာသော' },
  { id: 'n3q30', level: 'N3', skill: 'grammar', question: '説明が ___ で分かりやすい。', options: ['具体的', '抽象的', '消極的', '積極的'], correctIndex: 0, explanation: '具体的（ぐたいてき）= တိတိကျကျဖြစ်သော' },
  { id: 'n3q31', level: 'N3', skill: 'reading', question: '筆者は何が大切だと言っていますか。', passage: '日本語の上達には、毎日少しずつ続けることが大切です。一度にたくさん勉強するより、具体的な目標を決めて続ける方が効果的です。', options: ['一度にたくさん勉強すること', '毎日少しずつ続けること', '目標を決めないこと', '休まず勉強すること'], correctIndex: 1, explanation: '毎日少しずつ続けることが大切' },
  { id: 'n3q32', level: 'N3', skill: 'vocab', question: '「謙虚」の意味は？', options: ['နှိမ့်ချသော', 'ခေါင်းမာသော', 'လိမ္မာသော', 'ရဲရင့်သော'], correctIndex: 0, explanation: '謙虚（けんきょ）= နှိမ့်ချသော ⇔ 頑固' },
  { id: 'n3q33', level: 'N3', skill: 'grammar', question: '彼の話は ___ で信じられない。', options: ['曖昧', '明確', '具体', '率直'], correctIndex: 0, explanation: '曖昧（あいまい）= မရေရာသော' },
  { id: 'n3q34', level: 'N3', skill: 'listening', question: '聞こえた言葉は？', speakText: 'ぐうぜんあいました', options: ['偶然会った', '必然会った', '頻繁会った', '突然会った'], correctIndex: 0, explanation: '偶然（ぐうぜん）= တိုက်ဆိုင်မှု' },
];
