// N4 Quiz bank
export const n4Quiz = [
  { id: 'n4q01', level: 'N4', skill: 'vocab', question: '「約束」の読み方は？', options: ['やくそく', 'そうだん', 'れんらく', 'しょうたい'], correctIndex: 0, explanation: '約束（やくそく）= ကတိ' },
  { id: 'n4q02', level: 'N4', skill: 'vocab', question: '「会議」の意味は？', options: ['ခရီးစဉ်', 'အစည်းအဝေး', 'အားလပ်ရက်', 'လစာ'], correctIndex: 1, explanation: '会議（かいぎ）= အစည်းအဝေး' },
  { id: 'n4q03', level: 'N4', skill: 'vocab', question: '「地震」の読み方は？', options: ['じしん', 'たいふう', 'じこ', 'びょうき'], correctIndex: 0, explanation: '地震（じしん）= ငလျင်' },
  { id: 'n4q04', level: 'N4', skill: 'vocab', question: '「貯金」の意味は？', options: ['စုဆောင်းငွေ', 'လစာ', 'မုန့်ဖိုး', 'ဈေးနှုန်း'], correctIndex: 0, explanation: '貯金（ちょきん）= စုဆောင်းငွေ' },
  { id: 'n4q05', level: 'N4', skill: 'vocab', question: '「看板」の読み方は？ (bonus)', options: ['かんばん', 'こうこく', 'きじ', 'ほうそう'], correctIndex: 0, explanation: '看板（かんばん）= ဆိုင်းဘုတ်' },
  { id: 'n4q06', level: 'N4', skill: 'grammar', question: '雨が降っている ___ 、出かけます。', options: ['のに', 'ても', 'ので', 'から'], correctIndex: 1, explanation: '〜ても = even if (မိုးရွာနေပေမယ့်လည်း ထွက်မယ်)' },
  { id: 'n4q07', level: 'N4', skill: 'grammar', question: '日本へ行く ___ 、パスポートが要ります。', options: ['ために', 'ように', 'ままに', 'ところに'], correctIndex: 0, explanation: '〜ために = in order to / because of reason' },
  { id: 'n4q08', level: 'N4', skill: 'grammar', question: '彼は来る ___ 言いました。', options: ['と', 'に', 'へ', 'が'], correctIndex: 0, explanation: '引用 + と (〜と言いました = ...လို့ပြောတယ်)' },
  { id: 'n4q09', level: 'N4', skill: 'grammar', question: 'この本は ___ てもいいですか。', options: ['借り', '借りて', '借りる', '借りた'], correctIndex: 0, explanation: 'ます-stem + てもいい = may do (借りてもいい)' },
  { id: 'n4q10', level: 'N4', skill: 'grammar', question: '薬を飲ま ___ なりません。', options: ['なければ', 'なくては', 'ないで', 'なさ'], correctIndex: 0, explanation: '〜なければなりません = must (飲まなければなりません)' },
  { id: 'n4q11', level: 'N4', skill: 'reading', question: '男の人はどうして遅れましたか。', passage: '今朝、電車が事故で止まりました。男の人は会社に電話して、30分遅れて着きました。', options: ['寝坊したから', '電車が止まったから', '道に迷ったから', '電話したから'], correctIndex: 1, explanation: '電車が事故で止まりました = ရထားမတော်တဆမှုကြောင့်ရပ်သွားတယ်' },
  { id: 'n4q12', level: 'N4', skill: 'reading', question: '男の人は何分遅れましたか。', passage: '今朝、電車が事故で止まりました。男の人は会社に電話して、30分遅れて着きました。', options: ['10分', '20分', '30分', '1時間'], correctIndex: 2, explanation: '30分遅れて着きました' },
  { id: 'n4q13', level: 'N4', skill: 'listening', question: '聞こえた天気予報は？', speakText: 'あしたは雨でしょう', options: ['晴れでしょう', '雨でしょう', '曇りでしょう', '雪でしょう'], correctIndex: 1, explanation: '雨（あめ）でしょう = မိုးရွာမယ်ထင်တယ်' },
  { id: 'n4q14', level: 'N4', skill: 'listening', question: '女の人は何を頼みましたか。', speakText: 'コーヒーを二つください', options: ['コーヒーを一つ', 'コーヒーを二つ', '紅茶を二つ', 'ジュースを二つ'], correctIndex: 1, explanation: 'コーヒーを二つください' },
  { id: 'n4q15', level: 'N4', skill: 'vocab', question: '「残業」の意味は？', options: ['အချိန်ပိုအလုပ်', 'အစည်းအဝေး', 'အလုပ်ခရီးစဉ်', 'လစာ'], correctIndex: 0, explanation: '残業（ざんぎょう）= အချိန်ပိုအလုပ်' },
  { id: 'n4q16', level: 'N4', skill: 'grammar', question: '子供 ___ 分かる話です。', options: ['に', 'でも', 'さえ', 'しか'], correctIndex: 1, explanation: '子供でも分かる = ကလေးတောင် နားလည်တယ် (〜でも = even)' },
  { id: 'n4q17', level: 'N4', skill: 'vocab', question: '「領収書」の意味は？', options: ['ပြေစာ', 'သတင်းစာ', 'မဂ္ဂဇင်း', 'စာအုပ်'], correctIndex: 0, explanation: '領収書（りょうしゅうしょ）= ပြေစာ' },
  { id: 'n4q18', level: 'N4', skill: 'vocab', question: '「特急」の読み方は？', options: ['とっきゅう', 'きゅうこう', 'しんかんせん', 'ざんぎょう'], correctIndex: 0, explanation: '特急（とっきゅう）= အမြန်ရထား (ထူး)' },
  { id: 'n4q19', level: 'N4', skill: 'grammar', question: '病気 ___ 会社を休みました。', options: ['で', 'を', 'に', 'へ'], correctIndex: 0, explanation: '原因 + で (病気で = နေမကောင်းလို့)' },
  { id: 'n4q20', level: 'N4', skill: 'grammar', question: '駅 ___ 着きました。', options: ['に', 'を', 'が', 'と'], correctIndex: 0, explanation: '到着点 + に (駅に着いた)' },
  { id: 'n4q21', level: 'N4', skill: 'reading', question: 'ホテルは何階ですか。', passage: 'ホテルは5階です。部屋は501号です。フロントは1階です。', options: ['1階', '5階', '501階', '5号室'], correctIndex: 1, explanation: 'ホテルは5階です' },
  { id: 'n4q22', level: 'N4', skill: 'listening', question: '聞こえた時刻は？', speakText: 'でんしゃはまいあさ七時半に出ます', options: ['6時半', '七時半', '8時', '七時'], correctIndex: 1, explanation: '七時半（しちじはん）に出ます' },
  { id: 'n4q23', level: 'N4', skill: 'vocab', question: '「面接」の意味は？', options: ['အင်တာဗျူး', 'အစည်းအဝေး', 'ကြိုတင်မှာယူမှု', 'တိုင်ပင်မှု'], correctIndex: 0, explanation: '面接（めんせつ）= အင်တာဗျူး' },
  { id: 'n4q24', level: 'N4', skill: 'grammar', question: 'この薬は一日三回食後 ___ 飲んでください。', options: ['に', 'を', 'へ', 'が'], correctIndex: 0, explanation: '食後に = အစာစားပြီးနောက်' },
  { id: 'n4q25', level: 'N4', skill: 'vocab', question: '「定期券」の意味は？', options: ['လစဉ်လက်မှတ်', 'လက်မှတ်', 'ရထားဘူတာ', 'ယာဉ်စီးခ'], correctIndex: 0, explanation: '定期券（ていききっぷ）= လစဉ်လက်မှတ်' },
  { id: 'n4q26', level: 'N4', skill: 'vocab', question: '「気をつける」の意味は？', options: ['သတိထားသည်', 'စိတ်ဝင်စားသည်', 'သဘောကျသည်', 'စိတ်ထဲထားသည်'], correctIndex: 0, explanation: '気をつける = သတိထားသည်' },
  { id: 'n4q27', level: 'N4', skill: 'grammar', question: '会議に遅れ ___ 、すみません。', options: ['まして', 'ましては', 'そうで', 'ようで'], correctIndex: 0, explanation: '遅れまして = နောက်ကျတဲ့အတွက် (polite)' },
  { id: 'n4q28', level: 'N4', skill: 'grammar', question: '明日は雨が降る ___ です。', options: ['そう', 'ため', 'まま', 'ところ'], correctIndex: 0, explanation: 'verb-dict + そうです = hearsay (ရွာမယ်လို့ကြားတယ်)' },
  { id: 'n4q29', level: 'N4', skill: 'reading', question: '男の人はこれから何をしますか。', passage: '昼ご飯の後、男の人は銀行へ行きます。それから会社に戻ります。', options: ['銀行へ行く', '会社を出る', '昼ご飯を食べる', '家に帰る'], correctIndex: 0, explanation: '銀行へ行きます。それから会社に戻ります' },
  { id: 'n4q30', level: 'N4', skill: 'listening', question: '聞こえた番号は？', speakText: '三番線に電車がきます', options: ['一番線', '二番線', '三番線', '四番線'], correctIndex: 2, explanation: '三番線（さんばんせん）に' },
  { id: 'n4q31', level: 'N4', skill: 'vocab', question: '「卒業」の読み方は？', options: ['そつぎょう', 'にゅうがく', 'たいがく', 'しゅうしょく'], correctIndex: 0, explanation: '卒業（そつぎょう）= ကျောင်းပြီးခြင်း' },
  { id: 'n4q32', level: 'N4', skill: 'grammar', question: 'このボタンを ___ ください。', options: ['押して', '押す', '押し', '押した'], correctIndex: 0, explanation: '〜てください (押してください)' },
  { id: 'n4q33', level: 'N4', skill: 'vocab', question: '「診察」の読み方は？', options: ['しんさつ', 'しんさく', 'ちんさつ', 'しんだん'], correctIndex: 0, explanation: '診察（しんさつ）= ဆေးစစ်မှုခံယူခြင်း' },
  { id: 'n4q34', level: 'N4', skill: 'grammar', question: '病気 ___ 会社を休みました。', options: ['が', 'を', 'で', 'に'], correctIndex: 2, explanation: '原因 + で (病気で = နေမကောင်းလို့)' },
  { id: 'n4q35', level: 'N4', skill: 'reading', question: '男の人はなぜ病院へ行きましたか。', passage: '朝から頭が痛かったので、男の人は会社を休んで病院へ行きました。診察の結果、風邪でした。', options: ['頭が痛かったから', '会社が休みだから', '風邪が治ったから', '薬が欲しかったから'], correctIndex: 0, explanation: '朝から頭が痛かったので' },
  { id: 'n4q36', level: 'N4', skill: 'vocab', question: '「結婚式」の読み方は？', options: ['けっこんしき', 'けっこんし', 'けつこんしき', 'けっこんじき'], correctIndex: 0, explanation: '結婚式（けっこんしき）= မင်္ဂလာဆောင်ပွဲ' },
  { id: 'n4q37', level: 'N4', skill: 'grammar', question: '会議に ___ してください。', options: ['出席', '欠席', '遅刻', '早退'], correctIndex: 0, explanation: '出席（しゅっせき）してください = တက်ရောက်ပေးပါ' },
  { id: 'n4q38', level: 'N4', skill: 'listening', question: '聞こえた言葉は？', speakText: 'しゅっちょうにいきます', options: ['旅行に行く', '出張に行く', '転勤する', '残業する'], correctIndex: 1, explanation: '出張（しゅっちょう）= အလုပ်ကိစ္စခရီး' },
];
