// N5 Quiz bank — { id, level, skill, question, speakText?, passage?, options[], correctIndex, explanation, mediaUrl? }
// skills: vocab | grammar | reading | listening
export const n5Quiz = [
  // ---- Vocabulary ----
  { id: 'n5q01', level: 'N5', skill: 'vocab', question: '「猫」の読み方は？', options: ['ねこ', 'いぬ', 'とり', 'さかな'], correctIndex: 0, explanation: '猫（ねこ）= ကြောင်' },
  { id: 'n5q02', level: 'N5', skill: 'vocab', question: '「食べる」の意味は？', options: ['သောက်သည်', 'စားသည်', 'သွားသည်', 'လာသည်'], correctIndex: 1, explanation: '食べる（たべる）= စားသည်' },
  { id: 'n5q03', level: 'N5', skill: 'vocab', question: '「学校」の読み方は？', options: ['がっこう', 'びょういん', 'ぎんこう', 'としょかん'], correctIndex: 0, explanation: '学校（がっこう）= ကျောင်း' },
  { id: 'n5q04', level: 'N5', skill: 'vocab', question: '「赤い」の意味は？', options: ['ပြာသော', 'နီသော', 'ဖြူသော', 'မည်းသော'], correctIndex: 1, explanation: '赤い（あかい）= နီသော' },
  { id: 'n5q05', level: 'N5', skill: 'vocab', question: '「静か」の反対は？', options: ['にぎやか', 'きれい', 'ゆうめい', 'しんせつ'], correctIndex: 0, explanation: '静か（しずか, တိတ်ဆိတ်သော）⇔ 賑やか（にぎやか, စည်ကားသော）' },
  { id: 'n5q06', level: 'N5', skill: 'vocab', question: '「明日」の読み方は？', options: ['あした', 'きょう', 'きのう', 'あさって'], correctIndex: 0, explanation: '明日（あした）= မနက်ဖြန်' },
  { id: 'n5q07', level: 'N5', skill: 'vocab', question: '「お金」の意味は？ (お金)', options: ['ပိုက်ဆံ', 'အချိန်', 'လူ', 'ရေ'], correctIndex: 0, explanation: 'お金（おかね）= ပိုက်ဆံ' },
  { id: 'n5q08', level: 'N5', skill: 'vocab', question: '「 Nihon 」の正しい書き方は？', options: ['日本', '日本語', '日曜日', '本人'], correctIndex: 0, explanation: '日本（にほん/にっぽん）= ဂျပန်နိုင်ငံ' },
  // ---- Grammar ----
  { id: 'n5q09', level: 'N5', skill: 'grammar', question: 'わたし ___ 学生です。', options: ['は', 'が', 'を', 'に'], correctIndex: 0, explanation: 'X は Y です = X က Y ဖြစ်သည် (topic は)' },
  { id: 'n5q10', level: 'N5', skill: 'grammar', question: 'ご飯 ___ 食べます。', options: ['を', 'に', 'へ', 'で'], correctIndex: 0, explanation: 'Object + を + verb (ご飯を食べます = ထမင်းစားသည်)' },
  { id: 'n5q11', level: 'N5', skill: 'grammar', question: '学校 ___ 行きます。', options: ['に', 'を', 'が', 'と'], correctIndex: 0, explanation: 'Place + に + 行きます (destination に)' },
  { id: 'n5q12', level: 'N5', skill: 'grammar', question: '友達 ___ 電話します。', options: ['に', 'を', 'へ', 'が'], correctIndex: 0, explanation: '相手 + に (တစ်စုံတစ်ယောက်ကို → に)' },
  { id: 'n5q13', level: 'N5', skill: 'grammar', question: '図書館 ___ 本を読みます。', options: ['で', 'に', 'へ', 'を'], correctIndex: 0, explanation: 'Action の場所 + で (図書館で = စာကြည့်တိုက်မှာ)' },
  { id: 'n5q14', level: 'N5', skill: 'grammar', question: 'これは ___ 本ですか。', options: ['だれの', 'なんの', 'どこの', 'いくつの'], correctIndex: 0, explanation: 'だれの = ဘယ်သူ့ဟာလဲ (possession)' },
  { id: 'n5q15', level: 'N5', skill: 'grammar', question: '昨日、映画を ___。', options: ['見ました', '見ます', '見たい', '見ない'], correctIndex: 0, explanation: '昨日 (past) → ました (past polite)' },
  { id: 'n5q16', level: 'N5', skill: 'grammar', question: '日本語が ___ たいです。', options: ['話し', '話す', '話して', '話した'], correctIndex: 0, explanation: 'ます-stem + たい = want to (話したい)' },
  // ---- Reading ----
  { id: 'n5q17', level: 'N5', skill: 'reading', question: 'たなかさんは何歳ですか。', passage: 'はじめまして。わたしは たなかです。20歳です。学生です。まいあさ 7時に おきます。', options: ['18歳', '20歳', '7歳', '学生'], correctIndex: 1, explanation: '20歳（はたち）です と書いてある' },
  { id: 'n5q18', level: 'N5', skill: 'reading', question: 'たなかさんは朝何時に起きますか。', passage: 'はじめまして。わたしは たなかです。20歳です。学生です。まいあさ 7時に おきます。', options: ['6時', '7時', '8時', '20時'], correctIndex: 1, explanation: 'まいあさ 7時に おきます' },
  // ---- Listening (speakText を TTS で再生) ----
  { id: 'n5q19', level: 'N5', skill: 'listening', question: '聞こえた言葉は？', speakText: 'おはようございます', options: ['おはようございます', 'こんばんは', 'おやすみなさい', 'さようなら'], correctIndex: 0, explanation: 'おはようございます = မင်္ဂလာနံနက်ခင်း' },
  { id: 'n5q20', level: 'N5', skill: 'listening', question: '聞こえた数字は？', speakText: 'きっぷを二枚ください', options: ['一枚', '二枚', '三枚', '切符なし'], correctIndex: 1, explanation: '二枚（にまい）= ၂ စောင်' },
  { id: 'n5q21', level: 'N5', skill: 'listening', question: '聞こえた時間は？', speakText: 'じゅぎょうは九時からです', options: ['7時から', '8時から', '九時から', '10時から'], correctIndex: 2, explanation: '九時（くじ）から = ၉ နာရီကနေ' },
  { id: 'n5q22', level: 'N5', skill: 'vocab', question: '「大きい」の反対は？', options: ['小さい', '新しい', '古い', '長い'], correctIndex: 0, explanation: '大きい（おおきい) ⇔ 小さい（ちいさい)' },
  { id: 'n5q23', level: 'N5', skill: 'vocab', question: '「犬」の読み方は？', options: ['いぬ', 'ねこ', 'とり', 'うさぎ'], correctIndex: 0, explanation: '犬（いぬ）= ခွေး' },
  { id: 'n5q24', level: 'N5', skill: 'vocab', question: '「水」の意味は？', options: ['မီး', 'ရေ', 'လေ', 'မြေ'], correctIndex: 1, explanation: '水（みず）= ရေ' },
  { id: 'n5q25', level: 'N5', skill: 'vocab', question: '「新しい」の反対は？', options: ['古い', '大きい', '小さい', '長い'], correctIndex: 0, explanation: '新しい（あたらしい) ⇔ 古い（ふるい)' },
  { id: 'n5q26', level: 'N5', skill: 'grammar', question: '私の ___ は田中です。', options: ['名前', '本', '車', '水'], correctIndex: 0, explanation: '名前（なまえ）= နာမည်' },
  { id: 'n5q27', level: 'N5', skill: 'grammar', question: '毎朝パンを ___。', options: ['食べます', '飲みます', '読みます', '書きます'], correctIndex: 0, explanation: 'パン (bread) → 食べます' },
  { id: 'n5q28', level: 'N5', skill: 'grammar', question: '昨日どこ ___ 行きましたか。', options: ['へ', 'を', 'が', 'と'], correctIndex: 0, explanation: 'destination + へ (どこへ = ဘယ်ကို)' },
  { id: 'n5q29', level: 'N5', skill: 'reading', question: '山田さんは土曜日に何をしましたか。', passage: '土曜日に友達と映画を見ました。日曜日は家で休みました。', options: ['映画を見た', '買い物をした', '勉強した', '泳いだ'], correctIndex: 0, explanation: '土曜日に友達と映画を見ました' },
  { id: 'n5q30', level: 'N5', skill: 'listening', question: '聞こえた言葉は？', speakText: 'お名前は何ですか', options: ['お名前は何ですか', 'おいくつですか', 'どこから来ましたか', '何をしますか'], correctIndex: 0, explanation: 'お名前は何ですか = နာမည်ဘယ်လိုခေါ်လဲ' },
  { id: 'n5q31', level: 'N5', skill: 'vocab', question: '「寒い」の反対は？', options: ['暑い', '熱い', '暖かい', '涼しい'], correctIndex: 0, explanation: '寒い（さむい) ⇔ 暑い（あつい) — ရာသီဥတု' },
  { id: 'n5q32', level: 'N5', skill: 'grammar', question: 'もうご飯を ___ か。', options: ['食べた', '食べる', '食べない', '食べよう'], correctIndex: 0, explanation: 'もう〜たか = already…? (စားပြီးပြီလား)' },
  { id: 'n5q33', level: 'N5', skill: 'vocab', question: '「お金」の意味は？', options: ['ပိုက်ဆံ', 'အချိန်', 'လူ', '水'], correctIndex: 0, explanation: 'お金（おかね）= ပိုက်ဆံ' },
  { id: 'n5q34', level: 'N5', skill: 'vocab', question: '「肩」の読み方は？', options: ['かた', 'うで', 'ゆび', 'くび'], correctIndex: 0, explanation: '肩（かた）= ပခုံး' },
  { id: 'n5q35', level: 'N5', skill: 'vocab', question: '「醤油」の意味は？', options: ['ပဲငံပြာရည်', 'ဆား', 'သကြား', 'ရှာလကာရည်'], correctIndex: 0, explanation: '醤油（しょうゆ）= ပဲငံပြာရည်' },
  { id: 'n5q36', level: 'N5', skill: 'grammar', question: '私は日本語 ___ 勉強します。', options: ['を', 'に', 'へ', 'が'], correctIndex: 0, explanation: 'Object + を (日本語を勉強します)' },
  { id: 'n5q37', level: 'N5', skill: 'grammar', question: '毎晩シャワーを ___。', options: ['浴びます', '飲みます', '読みます', '書きます'], correctIndex: 0, explanation: 'シャワーを浴びます = ရေချိုးတယ်' },
  { id: 'n5q38', level: 'N5', skill: 'grammar', question: 'あの人は ___ ですか。', options: ['だれ', 'なに', 'どこ', 'いつ'], correctIndex: 0, explanation: 'あの人はだれですか = ဟိုလူကဘယ်သူလဲ' },
  { id: 'n5q39', level: 'N5', skill: 'reading', question: '日曜日は何をしましたか。', passage: '土曜日は友達と買い物をしました。日曜日はうちでテレビを見ました。', options: ['買い物をした', 'テレビを見た', '映画を見た', '泳いだ'], correctIndex: 1, explanation: '日曜日はうちでテレビを見ました' },
  { id: 'n5q40', level: 'N5', skill: 'listening', question: '聞こえた挨拶は？', speakText: 'こんばんは', options: ['おはよう', 'こんにちは', 'こんばんは', 'おやすみ'], correctIndex: 2, explanation: 'こんばんは = မင်္ဂလာညချမ်း' },
  { id: 'n5q41', level: 'N5', skill: 'vocab', question: '「もっと」の意味は？', options: ['ပိုပြီး', 'အမြဲတမ်း', 'သေချာပေါက်', 'လုံးဝ'], correctIndex: 0, explanation: 'もっと = ပိုပြီး' },
  { id: 'n5q42', level: 'N5', skill: 'grammar', question: 'ここで写真を ___ ください。', options: ['撮って', '撮る', '撮り', '撮った'], correctIndex: 0, explanation: '〜てください request (撮ってください)' },
  { id: 'n5q43', level: 'N5', skill: 'vocab', question: '「切手」の読み方は？', options: ['きって', 'きっぷ', 'ふうとう', 'はがき'], correctIndex: 0, explanation: '切手（きって）= တံဆိပ်ခေါင်း' },
  { id: 'n5q44', level: 'N5', skill: 'grammar', question: 'バス ___ 降ります。', options: ['を', 'に', 'で', 'から'], correctIndex: 3, explanation: '起点 + から (バスから降ります = ဘတ်စ်ကားပေါ်ကဆင်းတယ်)' },
  { id: 'n5q45', level: 'N5', skill: 'listening', question: '聞こえた言葉は？', speakText: 'おてらにいきました', options: ['じんじゃに行った', 'お寺に行った', 'こうえんに行った', 'がっこうに行った'], correctIndex: 1, explanation: 'お寺（おてら）= ဘုန်းကြီးကျောင်း' },
  { id: 'n5q46', level: 'N5', skill: 'vocab', question: '「封筒」の読み方は？', options: ['ふうとう', 'きって', 'てがみ', 'はこ'], correctIndex: 0, explanation: '封筒（ふうとう）= စာအိတ်' },
  { id: 'n5q47', level: 'N5', skill: 'grammar', question: 'お金を ___。', options: ['払います', '切ります', '開けます', '閉めます'], correctIndex: 0, explanation: 'お金を払います (はらいます = ပေးချေသည်)' },
  { id: 'n5q48', level: 'N5', skill: 'listening', question: '聞こえた言葉は？', speakText: 'きってをかいました', options: ['きっぷを買った', '切手を買った', 'かばんを買った', 'ほんを買った'], correctIndex: 1, explanation: '切手（きって）を買いました' },
];
